### ISSUE TITLE
'unknown opcode' when trying to load the pre-trained model.

### ISSUE THREAD

**Issue by ronitkishore** [MRE-Lab-UMD/abd-skin-segmentation#1]
Hi,

This is what I'm getting:
```
File "<ipython-input-29-e723bb360a5a>", line 3, in <lambda>
SystemError: unknown opcode
```

I expect this to be a Python/Keras version configuration issue. Do you have more details of the versions you used when saving the model?

**Comment by anirudhtopiwala** [comment]
Hi, 
The keras version used to train the model is 2.3.1. Although you can use the dataset which is publicly available and the the same network configuration to retrain the model.
