### ISSUE TITLE
Issue loading pretrained model

### ISSUE THREAD

**Issue by EnricoBeltramo** [MRE-Lab-UMD/abd-skin-segmentation#2]
I have some issue to load the pretrained model (same error of #1 ), either with keras 2.3.1
If I create the model copying the structure in https://github.com/MRE-Lab-UMD/abd-skin-segmentation/blob/master/UNET%20and%20Features/U-Net.ipynb
and load only weights, it say that the structure doesn't match (different number of layers).
Is it possible to have the structure of model in order to load the weights without the re-train again?

**Comment by lydiazoghbi** [comment]
Sorry for the late response. I believe we accidentally pushed one of the models we were experimenting with, which does not correspond to the final .h5 model we provided. I pushed the old model back again, let us know if you face any other issues.
