### ISSUE TITLE
Loading model into live script

### ISSUE THREAD

**Issue by lydiazoghbi** [MRE-Lab-UMD/abd-skin-segmentation#3]
Received multiple complaints that it doesn't really load the model. Typically it reports bad marshal data. Either the model is corrupt or it needs to be loaded differently (load weights into pre-existing model rather than loading trained model directly). Need to look into that.

**Comment by anirudhtopiwala** [comment]
I think the errors are because of dependency issues. I have updated the Readme to reflect the order in which dependencies need to be installed in a fresh virtual environment. I have tested this locally and it seems to be working perfectly.
