### ISSUE TITLE
Dataset in trash?

### ISSUE THREAD

**Issue by lydiazoghbi** [MRE-Lab-UMD/abd-skin-segmentation#4]
Need to relocate datasets into a different drive. I can open the link but can't download from terminal.

**Comment by pbdahzou** [comment]
I cannot download the data too

**Comment by lydiazoghbi** [comment]
You can download the files by directly accessing the links from your browser. I'm pasting the links here.
https://drive.google.com/uc?id=1MnBW_OJqrTmzwc23YI5NK_y_l4zk9JGJ
https://drive.google.com/uc?id=1xzYn4Rat4z2LA5zQW7JTfvA1bosz7oM-

**Comment by pbdahzou** [comment]
> You can download the files by directly accessing the links from your browser. I'm pasting the links here.
> https://drive.google.com/uc?id=1MnBW_OJqrTmzwc23YI5NK_y_l4zk9JGJ
> https://drive.google.com/uc?id=1xzYn4Rat4z2LA5zQW7JTfvA1bosz7oM-

Now I can download the files, thank you very much!
