### ISSUE TITLE
How to convert your model to TorchScript

### ISSUE THREAD

**Issue by luongdv3vts** [MRE-Lab-UMD/abd-skin-segmentation#8]
I want to use and load this model on android app. 
How to convert this .pth extension model into torchvision for load model on android and how can I use your skin color detection model to conduct the experiment of skin color detection on a android?
Thank you!

**Comment by luongdv3vts** [comment]
up

**Comment by luongdv3vts** [comment]
up

**Comment by coallar** [comment]
> up

do you know which version of tf is suitable for this project?

**Comment by lydiazoghbi** [comment]
#

> I want to use and load this model on android app. How to convert this .pth extension model into torchvision for load model on android and how can I use your skin color detection model to conduct the experiment of skin color detection on a android? Thank you!

This is super late but putting it out there if anybody else is interested. This [embedded link](https://discuss.pytorch.org/t/how-to-convert-pretrained-pth-extension-pytorch-model-into-torchvision-model-to-load-on-android/66935) should help.

**Comment by lydiazoghbi** [comment]
> > up
> 
> do you know which version of tf is suitable for this project?

Unfortunately I don't have that information anymore. See #5, and #1 at least for the Keras version, should narrow it down a bit.
